services:
  polykey-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
      args:
        - COMPRESS_BINARIES=false  # Enable for production
    ports:
      - "50051:50051"
    environment:
      - POLYKEY_ENV=docker
      - POLYKEY_LOG_LEVEL=debug
    networks:
      - polykey-network
    # Optimized healthcheck - less frequent checks
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    # Resource limits for better container management
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Restart policy for resilience
    restart: unless-stopped

networks:
  polykey-network:
    driver: bridge
    # Add network configuration for better performance
    driver_opts:
      com.docker.network.bridge.name: polykey-br0
      com.docker.network.driver.mtu: 1500