// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: polykey.proto

package polykey

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bot represents the complete configuration of a single chatbot.
// This message is used to transfer bot data between services and to the client.
type Bot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	ModelProvider string                 `protobuf:"bytes,5,opt,name=model_provider,json=modelProvider,proto3" json:"model_provider,omitempty"` // e.g., "openai", "groq"
	ApiKeyIsSet   bool                   `protobuf:"varint,6,opt,name=api_key_is_set,json=apiKeyIsSet,proto3" json:"api_key_is_set,omitempty"`  // Indicates if a key is stored, without exposing the key itself.
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bot) Reset() {
	*x = Bot{}
	mi := &file_polykey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bot) ProtoMessage() {}

func (x *Bot) ProtoReflect() protoreflect.Message {
	mi := &file_polykey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bot.ProtoReflect.Descriptor instead.
func (*Bot) Descriptor() ([]byte, []int) {
	return file_polykey_proto_rawDescGZIP(), []int{0}
}

func (x *Bot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bot) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Bot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bot) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *Bot) GetModelProvider() string {
	if x != nil {
		return x.ModelProvider
	}
	return ""
}

func (x *Bot) GetApiKeyIsSet() bool {
	if x != nil {
		return x.ApiKeyIsSet
	}
	return false
}

func (x *Bot) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Bot) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// --- RouteChat ---
type RouteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteChatRequest) Reset() {
	*x = RouteChatRequest{}
	mi := &file_polykey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteChatRequest) ProtoMessage() {}

func (x *RouteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polykey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteChatRequest.ProtoReflect.Descriptor instead.
func (*RouteChatRequest) Descriptor() ([]byte, []int) {
	return file_polykey_proto_rawDescGZIP(), []int{1}
}

func (x *RouteChatRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *RouteChatRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type RouteChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseChunk string                 `protobuf:"bytes,1,opt,name=response_chunk,json=responseChunk,proto3" json:"response_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteChatResponse) Reset() {
	*x = RouteChatResponse{}
	mi := &file_polykey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteChatResponse) ProtoMessage() {}

func (x *RouteChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polykey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteChatResponse.ProtoReflect.Descriptor instead.
func (*RouteChatResponse) Descriptor() ([]byte, []int) {
	return file_polykey_proto_rawDescGZIP(), []int{2}
}

func (x *RouteChatResponse) GetResponseChunk() string {
	if x != nil {
		return x.ResponseChunk
	}
	return ""
}

// --- CreateBot ---
type CreateBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	ModelProvider string                 `protobuf:"bytes,3,opt,name=model_provider,json=modelProvider,proto3" json:"model_provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBotRequest) Reset() {
	*x = CreateBotRequest{}
	mi := &file_polykey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotRequest) ProtoMessage() {}

func (x *CreateBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polykey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotRequest.ProtoReflect.Descriptor instead.
func (*CreateBotRequest) Descriptor() ([]byte, []int) {
	return file_polykey_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBotRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *CreateBotRequest) GetModelProvider() string {
	if x != nil {
		return x.ModelProvider
	}
	return ""
}

// --- GetBot & DeleteBot ---
type GetBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotRequest) Reset() {
	*x = GetBotRequest{}
	mi := &file_polykey_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotRequest) ProtoMessage() {}

func (x *GetBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polykey_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotRequest.ProtoReflect.Descriptor instead.
func (*GetBotRequest) Descriptor() ([]byte, []int) {
	return file_polykey_proto_rawDescGZIP(), []int{4}
}

func (x *GetBotRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type DeleteBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBotRequest) Reset() {
	*x = DeleteBotRequest{}
	mi := &file_polykey_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBotRequest) ProtoMessage() {}

func (x *DeleteBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polykey_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBotRequest.ProtoReflect.Descriptor instead.
func (*DeleteBotRequest) Descriptor() ([]byte, []int) {
	return file_polykey_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBotRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

// --- UpdateBot ---
type UpdateBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	ModelProvider string                 `protobuf:"bytes,4,opt,name=model_provider,json=modelProvider,proto3" json:"model_provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBotRequest) Reset() {
	*x = UpdateBotRequest{}
	mi := &file_polykey_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBotRequest) ProtoMessage() {}

func (x *UpdateBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polykey_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBotRequest.ProtoReflect.Descriptor instead.
func (*UpdateBotRequest) Descriptor() ([]byte, []int) {
	return file_polykey_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBotRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *UpdateBotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBotRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *UpdateBotRequest) GetModelProvider() string {
	if x != nil {
		return x.ModelProvider
	}
	return ""
}

// --- ListBots ---
type ListBotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBotsRequest) Reset() {
	*x = ListBotsRequest{}
	mi := &file_polykey_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBotsRequest) ProtoMessage() {}

func (x *ListBotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polykey_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBotsRequest.ProtoReflect.Descriptor instead.
func (*ListBotsRequest) Descriptor() ([]byte, []int) {
	return file_polykey_proto_rawDescGZIP(), []int{7}
}

// --- SetBotAPIKey ---
type SetBotAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"` // This field contains the sensitive key and must be handled securely.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBotAPIKeyRequest) Reset() {
	*x = SetBotAPIKeyRequest{}
	mi := &file_polykey_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBotAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBotAPIKeyRequest) ProtoMessage() {}

func (x *SetBotAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polykey_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBotAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*SetBotAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_polykey_proto_rawDescGZIP(), []int{8}
}

func (x *SetBotAPIKeyRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *SetBotAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

var File_polykey_proto protoreflect.FileDescriptor

const file_polykey_proto_rawDesc = "" +
	"\n" +
	"\rpolykey.proto\x12\apolykey\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa9\x02\n" +
	"\x03Bot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12%\n" +
	"\x0emodel_provider\x18\x05 \x01(\tR\rmodelProvider\x12#\n" +
	"\x0eapi_key_is_set\x18\x06 \x01(\bR\vapiKeyIsSet\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"A\n" +
	"\x10RouteChatRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\":\n" +
	"\x11RouteChatResponse\x12%\n" +
	"\x0eresponse_chunk\x18\x01 \x01(\tR\rresponseChunk\"r\n" +
	"\x10CreateBotRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\x12%\n" +
	"\x0emodel_provider\x18\x03 \x01(\tR\rmodelProvider\"&\n" +
	"\rGetBotRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\")\n" +
	"\x10DeleteBotRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\"\x89\x01\n" +
	"\x10UpdateBotRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12%\n" +
	"\x0emodel_provider\x18\x04 \x01(\tR\rmodelProvider\"\x11\n" +
	"\x0fListBotsRequest\"E\n" +
	"\x13SetBotAPIKeyRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey2\xa7\x03\n" +
	"\aPolyKey\x12D\n" +
	"\tRouteChat\x12\x19.polykey.RouteChatRequest\x1a\x1a.polykey.RouteChatResponse0\x01\x124\n" +
	"\tCreateBot\x12\x19.polykey.CreateBotRequest\x1a\f.polykey.Bot\x12.\n" +
	"\x06GetBot\x12\x16.polykey.GetBotRequest\x1a\f.polykey.Bot\x124\n" +
	"\tUpdateBot\x12\x19.polykey.UpdateBotRequest\x1a\f.polykey.Bot\x12>\n" +
	"\tDeleteBot\x12\x19.polykey.DeleteBotRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\bListBots\x12\x18.polykey.ListBotsRequest\x1a\f.polykey.Bot0\x01\x12D\n" +
	"\fSetBotAPIKey\x12\x1c.polykey.SetBotAPIKeyRequest\x1a\x16.google.protobuf.EmptyB.Z,github.com/SpoungeAI/polykey-service/polykeyb\x06proto3"

var (
	file_polykey_proto_rawDescOnce sync.Once
	file_polykey_proto_rawDescData []byte
)

func file_polykey_proto_rawDescGZIP() []byte {
	file_polykey_proto_rawDescOnce.Do(func() {
		file_polykey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polykey_proto_rawDesc), len(file_polykey_proto_rawDesc)))
	})
	return file_polykey_proto_rawDescData
}

var file_polykey_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_polykey_proto_goTypes = []any{
	(*Bot)(nil),                 // 0: polykey.Bot
	(*RouteChatRequest)(nil),    // 1: polykey.RouteChatRequest
	(*RouteChatResponse)(nil),   // 2: polykey.RouteChatResponse
	(*CreateBotRequest)(nil),    // 3: polykey.CreateBotRequest
	(*GetBotRequest)(nil),       // 4: polykey.GetBotRequest
	(*DeleteBotRequest)(nil),    // 5: polykey.DeleteBotRequest
	(*UpdateBotRequest)(nil),    // 6: polykey.UpdateBotRequest
	(*ListBotsRequest)(nil),     // 7: polykey.ListBotsRequest
	(*SetBotAPIKeyRequest)(nil), // 8: polykey.SetBotAPIKeyRequest
	(*timestamp.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*empty.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_polykey_proto_depIdxs = []int32{
	9,  // 0: polykey.Bot.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: polykey.Bot.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: polykey.PolyKey.RouteChat:input_type -> polykey.RouteChatRequest
	3,  // 3: polykey.PolyKey.CreateBot:input_type -> polykey.CreateBotRequest
	4,  // 4: polykey.PolyKey.GetBot:input_type -> polykey.GetBotRequest
	6,  // 5: polykey.PolyKey.UpdateBot:input_type -> polykey.UpdateBotRequest
	5,  // 6: polykey.PolyKey.DeleteBot:input_type -> polykey.DeleteBotRequest
	7,  // 7: polykey.PolyKey.ListBots:input_type -> polykey.ListBotsRequest
	8,  // 8: polykey.PolyKey.SetBotAPIKey:input_type -> polykey.SetBotAPIKeyRequest
	2,  // 9: polykey.PolyKey.RouteChat:output_type -> polykey.RouteChatResponse
	0,  // 10: polykey.PolyKey.CreateBot:output_type -> polykey.Bot
	0,  // 11: polykey.PolyKey.GetBot:output_type -> polykey.Bot
	0,  // 12: polykey.PolyKey.UpdateBot:output_type -> polykey.Bot
	10, // 13: polykey.PolyKey.DeleteBot:output_type -> google.protobuf.Empty
	0,  // 14: polykey.PolyKey.ListBots:output_type -> polykey.Bot
	10, // 15: polykey.PolyKey.SetBotAPIKey:output_type -> google.protobuf.Empty
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_polykey_proto_init() }
func file_polykey_proto_init() {
	if File_polykey_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polykey_proto_rawDesc), len(file_polykey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polykey_proto_goTypes,
		DependencyIndexes: file_polykey_proto_depIdxs,
		MessageInfos:      file_polykey_proto_msgTypes,
	}.Build()
	File_polykey_proto = out.File
	file_polykey_proto_goTypes = nil
	file_polykey_proto_depIdxs = nil
}
