server:
  port: "<your-server-port>"
  mode: "<your-environment>"
  tls:
    enabled: <true-or-false>
    cert_file: "<path-to-your-cert-file>"
    key_file: "<path-to-your-key-file>"

persistence:
  type: "neondb" # can be "neondb", "s3", or "cockroachdb"

aws:
  enabled: true
  region: "<your-aws-region>"
  s3_bucket: "<your-unique-bucket-name>"
  kms_key_arn: "<your-kms-key-arn>"

vault:
  address: "<your-vault-address>"
  token: "<your-vault-token>"

database:
  host: "<your-database-host>"
  port: "<your-database-port>"
  user: "<your-database-user>"
  password: "<your-database-password>"
  dbname: "polykey"
  sslmode: "require"

neondb:
  url: "postgresql://<user>:<password>@<host>:<port>/<dbname>?sslmode=require"

cockroachdb:
  url: "<your-cockroachdb-connection-string>"

LOCAL_MASTER_KEY: "<your-local-master-key>"

authorization:
  roles:
    admin:
      allowed_operations:
        - "/polykey.v2.PolykeyService/CreateKey"
        - "/polykey.v2.PolykeyService/RotateKey"
        - "/polykey.v2.PolykeyService/RevokeKey"
        - "/polykey.v2.PolykeyService/UpdateKeyMetadata"
        - "/polykey.v2.PolykeyService/GetKey"
        - "/polykey.v2.PolykeyService/GetKeyMetadata"
        - "/polykey.v2.PolykeyService/ListKeys"
    user:
      allowed_operations:
        - "/polykey.v2.PolykeyService/GetKey"
        - "/polykey.v2.PolykeyService/GetKeyMetadata"
        - "/polykey.v2.PolykeyService/ListKeys"
