# Polykey microservice configuration example

server:
  port: 50053
  mode: "development"
  tls:
    enabled: true
    client_auth: "RequireAndVerifyClientCert"


# defaults for local testing
persistence:
  type: neondb
  database:
    connection:
      max_conns: 25
      min_conns: 5
      max_conn_lifetime: 1h
      max_conn_idle_time: 5m
      health_check_period: 1m
    tls:
      enabled: false
    max_retries: 3
    retry_backoff: 1s

# if true, all configurations are bootstrapped from ssm
aws:
  enabled: true
  region: "<example-region>"
  s3_bucket: "<example-s3-bucket>"

authorization:
  roles:
    admin:
      - "<example-admin-role>"
    user:
      - "<example-user-role>"
  zero_trust:
    enforce_mtls_identity_match: true

# Optional overrides for secrets, local testing
default_kms_provider: "<example-kms-provider>"

client_credentials_path: "<example-client-credentials-path>"

bootstrap_secrets_base_path: "<example-bootstrap-secrets-base-path>"

spounge_ca: "<example-ca-arn>"
polykey_kms_arn: "<example-kms-arn>"
