server:
  port: 50053
  mode: "development"
  tls:
    enabled: true
    cert_file: "certs/cert_example.pem"
    key_file: "certs/key_example.pem"

persistence:
  type: "neondb"

aws:
  enabled: true
  region: "us-east-1"
  s3_bucket: "<your-s3-bucket-for-s3-persistence>"
  kms_key_arn: "<your-kms-key-arn-for-aws-kms-provider>"

authorization:
  roles:
    admin:
      allowed_operations: ["*"]
    premium_user:
      allowed_operations:
        - "create_key"
        - "get_key"
        - "list_keys"
        - "rotate_key"
    free_user:
      allowed_operations:
        - "create_key"
        - "get_key"
