// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: llm.proto

package llm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTextRequest) Reset() {
	*x = GenerateTextRequest{}
	mi := &file_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTextRequest) ProtoMessage() {}

func (x *GenerateTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTextRequest.ProtoReflect.Descriptor instead.
func (*GenerateTextRequest) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateTextRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GenerateTextRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateTextRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateTextRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

type TextCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	TokenCount    int32                  `protobuf:"varint,2,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextCandidate) Reset() {
	*x = TextCandidate{}
	mi := &file_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCandidate) ProtoMessage() {}

func (x *TextCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextCandidate.ProtoReflect.Descriptor instead.
func (*TextCandidate) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{1}
}

func (x *TextCandidate) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TextCandidate) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

type GenerateTextResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Candidates           []*TextCandidate       `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	PromptTokenUsage     int32                  `protobuf:"varint,2,opt,name=prompt_token_usage,json=promptTokenUsage,proto3" json:"prompt_token_usage,omitempty"`
	CompletionTokenUsage int32                  `protobuf:"varint,3,opt,name=completion_token_usage,json=completionTokenUsage,proto3" json:"completion_token_usage,omitempty"`
	TotalTokenUsage      int32                  `protobuf:"varint,4,opt,name=total_token_usage,json=totalTokenUsage,proto3" json:"total_token_usage,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GenerateTextResponse) Reset() {
	*x = GenerateTextResponse{}
	mi := &file_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTextResponse) ProtoMessage() {}

func (x *GenerateTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTextResponse.ProtoReflect.Descriptor instead.
func (*GenerateTextResponse) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateTextResponse) GetCandidates() []*TextCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *GenerateTextResponse) GetPromptTokenUsage() int32 {
	if x != nil {
		return x.PromptTokenUsage
	}
	return 0
}

func (x *GenerateTextResponse) GetCompletionTokenUsage() int32 {
	if x != nil {
		return x.CompletionTokenUsage
	}
	return 0
}

func (x *GenerateTextResponse) GetTotalTokenUsage() int32 {
	if x != nil {
		return x.TotalTokenUsage
	}
	return 0
}

var File_llm_proto protoreflect.FileDescriptor

const file_llm_proto_rawDesc = "" +
	"\n" +
	"\tllm.proto\x12\x03llm\x1a\x1cgoogle/protobuf/struct.proto\"\x90\x01\n" +
	"\x13GenerateTextRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12/\n" +
	"\x06params\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06params\"H\n" +
	"\rTextCandidate\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x1f\n" +
	"\vtoken_count\x18\x02 \x01(\x05R\n" +
	"tokenCount\"\xda\x01\n" +
	"\x14GenerateTextResponse\x122\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x12.llm.TextCandidateR\n" +
	"candidates\x12,\n" +
	"\x12prompt_token_usage\x18\x02 \x01(\x05R\x10promptTokenUsage\x124\n" +
	"\x16completion_token_usage\x18\x03 \x01(\x05R\x14completionTokenUsage\x12*\n" +
	"\x11total_token_usage\x18\x04 \x01(\x05R\x0ftotalTokenUsage2Q\n" +
	"\n" +
	"LLMService\x12C\n" +
	"\fGenerateText\x12\x18.llm.GenerateTextRequest\x1a\x19.llm.GenerateTextResponseB<Z:github.com/SpoungeAI/polykey-service/internal/adapters/llmb\x06proto3"

var (
	file_llm_proto_rawDescOnce sync.Once
	file_llm_proto_rawDescData []byte
)

func file_llm_proto_rawDescGZIP() []byte {
	file_llm_proto_rawDescOnce.Do(func() {
		file_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_proto_rawDesc), len(file_llm_proto_rawDesc)))
	})
	return file_llm_proto_rawDescData
}

var file_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_llm_proto_goTypes = []any{
	(*GenerateTextRequest)(nil),  // 0: llm.GenerateTextRequest
	(*TextCandidate)(nil),        // 1: llm.TextCandidate
	(*GenerateTextResponse)(nil), // 2: llm.GenerateTextResponse
	(*structpb.Struct)(nil),      // 3: google.protobuf.Struct
}
var file_llm_proto_depIdxs = []int32{
	3, // 0: llm.GenerateTextRequest.params:type_name -> google.protobuf.Struct
	1, // 1: llm.GenerateTextResponse.candidates:type_name -> llm.TextCandidate
	0, // 2: llm.LLMService.GenerateText:input_type -> llm.GenerateTextRequest
	2, // 3: llm.LLMService.GenerateText:output_type -> llm.GenerateTextResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_llm_proto_init() }
func file_llm_proto_init() {
	if File_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_proto_rawDesc), len(file_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_proto_goTypes,
		DependencyIndexes: file_llm_proto_depIdxs,
		MessageInfos:      file_llm_proto_msgTypes,
	}.Build()
	File_llm_proto = out.File
	file_llm_proto_goTypes = nil
	file_llm_proto_depIdxs = nil
}
